version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fs_report_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 